---
- name: Playbook to push organizations to controller
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    controller_hostname: "https://aap.lab.local/"
    controller_username: admin
    controller_password: Proteu690201
    controller_validate_certs: false
    controller_organizations:
      - name: Satellite
      - name: Default

  collections:
    - awx.awx
    - redhat_cop.controller_configuration

  tasks:
    - name: Ensure organizations exist in Controller
      ansible.builtin.include_role:
        name: controller_configuration.organizations
