---
- name: Playbook to push organizations to controller
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    controller_hostname: controller.node/
    controller_username: admin
    controller_password: Proteu690201
    controller_validate_certs: false
    controller_organizations:
      - name: Satellite
      - name: Default
  collections:
    - awx.awx
    - redhat_cop.controller_configuration
  roles:
    - redhat_cop.controller_configuration.organizations
...
