---
- name: Playbook to push organizations to controller
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    controller_hostname: "https://aap.lab.local/"   # ajuste conforme seu ambiente
    controller_username: "admin"
    controller_password: "Proteu690201"
    controller_validate_certs: false

    controller_organizations:
      - name: Satellite-2
      - name: Default

  collections:
    - awx.awx
    - redhat_cop.controller_configuration

  tasks:
    - name: Ensure organizations exist in Controller
      include_role:
        name: redhat_cop.controller_configuration.organizations
