---
- name: Create Organization
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  tasks:
    - name: Create Organization
      ansible.controller.organization:
        name: Satellite
        controller_host: https://aap.lab.local/
        controller_username: admin
        controller_password: Proteu690201
        validate_certs: false
...
